### ISSUE TITLE
source-map-loader print the source map json and fails

### ISSUE THREAD

**Issue by 64BitAsura** [webpack-contrib/source-map-loader#234]
<img width="824" alt="Screenshot 2024-03-27 at 01 33 43" src="https://github.com/webpack-contrib/source-map-loader/assets/6957824/b29c0943-6b7c-464b-84d0-cc3823a76ef5">

I used `source-map-loader` as instructed! I am getting crash saying `You may need an additional loader to handle the result of these loaders.`

**Comment by alexander-akait** [comment]
Thank you for creating this issue. However, issues need to follow one of our templates so that we can clearly understand your particular circumstances.

Please help us help you by recreating the issue using one of our templates.

It means you try to parse JSON file using `source-map-loader`, without additional infromation I can't help
